version: "3.9"
services:
  daemon:
    image: vividynamics/modem-resetter
    build: .
    command: python3 main.py
    restart: "always"
    environment:
      DEVICE_TYPE: $DEVICE_TYPE
      DEVICE_HOSTNAME: $DEVICE_HOSTNAME
      STRIP_PLUG_ALIAS: $STRIP_PLUG_ALIAS
      TIMEOUT: $TIMEOUT
      HEALTH_CHECK_INTERVAL: $HEALTH_CHECK_INTERVAL
      SHUTDOWN_DURATION: $SHUTDOWN_DURATION
      BOOT_DURATION: $BOOT_DURATION
      LOGGER_NAME: $LOGGER_NAME
      LOGGER_LEVEL: $LOGGER_LEVEL
      LOGGER_FORMAT: $LOGGER_FORMAT
      PING_ADDRESS_0: $PING_ADDRESS_0
      PING_ADDRESS_1: $PING_ADDRESS_1
      PING_ADDRESS_2: $PING_ADDRESS_2
      PING_ADDRESS_3: $PING_ADDRESS_3
      PING_ADDRESS_4: $PING_ADDRESS_4
      PING_ADDRESS_5: $PING_ADDRESS_5
      SAMPLE_WEBSITE_0: $SAMPLE_WEBSITE_0
      SAMPLE_WEBSITE_1: $SAMPLE_WEBSITE_1
      SAMPLE_WEBSITE_2: $SAMPLE_WEBSITE_2
